grafana:
    build: grafana
    ports: 
        - 3001:3000
    links:
        - influxdb:influxdb
    environment:
        GF_INSTALL_PLUGINS: "abhisant-druid-datasource,adremsoft-netcrunch-app,alexanderzobnin-zabbix-app,ayoungprogrammer-finance-datasource,belugacdn-app,bessler-pictureit-panel,bosun-app,briangann-datatable-panel,briangann-gauge-panel,btplc-alarm-box-panel,btplc-peak-report-panel,btplc-status-dot-panel,btplc-trend-box-panel,camptocamp-prometheus-alertmanager-datasource,citilogics-geoloop-panel,cloudflare-app,crate-datasource,dalmatinerdb-datasource,ddurieux-glpi-app,devicehive-devicehive-datasource,digiapulssi-breadcrumb-panel,digiapulssi-organisations-panel,digrich-bubblechart-panel,fastweb-openfalcon-datasource,fetzerch-sunandmoon-datasource,foursquare-clouderamanager-datasource,fzakaria-simple-annotations-datasource,gnocchixyz-gnocchi-datasource,grafana-azure-monitor-datasource,grafana-clock-panel,grafana-example-app,grafana-influxdb-08-datasource,grafana-kairosdb-datasource,grafana-piechart-panel,grafana-simple-json-datasource,grafana-worldmap-panel,gridprotectionalliance-openhistorian-datasource,gridprotectionalliance-osisoftpi-datasource,hawkular-datasource,ibm-apm-datasource,jasonlashua-prtg-datasource,jdbranham-diagram-panel,kentik-app,linksmart-hds-datasource,michaeldmoore-annunciator-panel,monasca-datasource,monitoringartist-monitoringart-datasource,mtanda-google-calendar-datasource,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,natel-discrete-panel,natel-influx-admin-panel,natel-plotly-panel,neocat-cal-heatmap-panel,novalabs-annotations-panel,ns1-app,ntop-ntopng-datasource,opennms-helm-app,percona-percona-app,petrslavotinek-carpetplot-panel,praj-ams-datasource,rackerlabs-blueflood-datasource,radensolutions-netxms-datasource,raintank-kubernetes-app,raintank-snap-app,raintank-worldping-app,ryantxu-ajax-panel,satellogic-3d-globe-panel,savantly-heatmap-panel,sidewinder-datasource,skydive-datasource,sni-pnp-datasource,stagemonitor-elasticsearch-app,udoprog-heroic-datasource,vertamedia-clickhouse-datasource,vonage-status-panel,voxter-app"
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: "true"
        GF_USERS_ALLOW_ORG_CREATE: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: "true"
        GF_DASHBOARDS_JSON_PATH: /opt/grafana
    volumes_from:
        - grafana-data

grafana-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/grafana
        - /var/log/grafana
        - /var/lib/grafana/plugins

influxdb:
    build: influxdb
    ports:
        - 8083:8083
        - 8086:8086
    environment:
        INFLUX_DATABASE: "telegraf"
        INLFUX_ADMIN_USER: "grafana"
        INFLUX_ADMIN_PASS: "grafana"
    volumes_from:
        - influxdb-data

influxdb-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/influxdb

telegraf:
    build: telegraf
    links:
        - influxdb:influxdb
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "telegraf"
    tty: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
